'use client';
import { useEffect, useState } from 'react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { workPlanSchema, type WorkPlan } from '@/lib/work-plan';
import { ActionPlanSuggestion, type PlanDraftContext } from '@/components/action-plan-suggestion';
import { changeActionCompletion } from '@/lib/work-action-view';

export function WorkPlanPanel({ value, question, busy, onSave, reviewed = false, suggestionContext }: { reviewed?: boolean; value?: WorkPlan; question: string; busy: boolean; onSave: (plan: WorkPlan | null) => boolean; suggestionContext?: PlanDraftContext }) {
  const [drafting, setDrafting] = useState(false), [hasPreview, setHasPreview] = useState(false);
  const [discardOpen, setDiscardOpen] = useState(false);
  const [open, setOpen] = useState(false), [draft, setDraft] = useState<WorkPlan>({ goal: '', actions: [] }), [initial, setInitial] = useState(''), [error, setError] = useState(''), [initialOutcome, setInitialOutcome] = useState('');
  const [recording, setRecording] = useState(false), [note, setNote] = useState(''), [minutesSaved, setMinutesSaved] = useState(''), [disposition, setDisposition] = useState<'used' | 'edited' | 'not-used'>('used'), [correction, setCorrection] = useState<'not-assessed' | 'confirmed' | 'rejected'>('not-assessed');
  const dirty = open && (recording ? JSON.stringify({ note, minutesSaved, disposition, correction }) !== initialOutcome : drafting || hasPreview || JSON.stringify(draft) !== initial);
  useEffect(() => { if (!dirty) return; const warn = (e: BeforeUnloadEvent) => { e.preventDefault(); e.returnValue = ''; }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  function close() { if (dirty) setDiscardOpen(true); else setOpen(false); }
  function edit() { const next = structuredClone(value ?? { goal: question.split('\n')[0].slice(0, 300), actions: [] }); setDraft(next); setInitial(JSON.stringify(next)); setRecording(false); setError(''); setHasPreview(false); setDrafting(false); setOpen(true); }
  function record() {
    const next = structuredClone(value ?? { goal: question.split('\n')[0].slice(0, 300), actions: [] });
    const previous = next.outcome;
    const fields = { note: previous?.note ?? '', minutesSaved: previous?.minutesSaved === undefined ? '' : String(previous.minutesSaved), disposition: previous?.disposition ?? 'used', correction: previous?.correction ?? 'not-assessed' };
    setDraft(next); setNote(fields.note); setMinutesSaved(fields.minutesSaved); setDisposition(fields.disposition); setCorrection(fields.correction); setInitialOutcome(JSON.stringify(fields)); setRecording(true); setError(''); setOpen(true);
  }
  function save(plan: WorkPlan) { const parsed = workPlanSchema.safeParse(plan); if (!parsed.success) { setError('Use a goal, nonempty actions, valid dates, and whole minutes from -100,000 to 100,000. Result use and action completion are recorded separately.'); return; } if (onSave(parsed.data)) setOpen(false); }
  const completed = value?.actions.filter(a => a.completedAt).length ?? 0;
  return <section className="work-plan" aria-label="Action plan">
    {value ? <><div className="work-plan-heading"><div><span className="work-kicker">YOUR ACTION PLAN</span><h3>{value.goal}</h3></div><span>{completed}/{value.actions.length} complete</span></div>
      <ul className="work-action-list">{value.actions.map(action => <li key={action.id}><label><input type="checkbox" aria-label={`${action.completedAt ? 'Reopen' : 'Complete'}: ${action.title}`} checked={!!action.completedAt} disabled={busy} onChange={e => { onSave(changeActionCompletion(value, action.id, e.target.checked)); }} /><span>{action.title}{action.due && <small>Planned for {action.due}</small>}</span></label></li>)}</ul>
      {!value.actions.length && !value.outcome && <p className="muted">Add a concrete next action to begin tracking this work.</p>}
      {value.outcome && <div className="work-outcome"><strong>Outcome recorded by you</strong><p>{{ used: 'Used', edited: 'Used with edits', 'not-used': 'Not used' }[value.outcome.disposition]}</p>{value.outcome.note && <p>{value.outcome.note}</p>}{reviewed && <p>Your assessment of a material correction: {value.outcome.correction}</p>}{value.outcome.minutesSaved !== undefined && <p>Estimated minutes saved: {value.outcome.minutesSaved}{value.outcome.minutesSaved < 0 ? ' (extra time spent)' : ''}</p>}</div>}
      <div className="work-plan-controls"><button className="subtle-button" disabled={busy} onClick={edit}>Edit action plan</button><button className="subtle-button" disabled={busy} onClick={record}>{value.outcome ? 'Edit result record' : 'Record outcome'}</button><button className="subtle-button" disabled={busy} onClick={() => { if (window.confirm('Remove this action plan and its recorded outcome? The answer will remain.')) onSave(null); }}>Remove plan</button></div>
    </> : <div className="work-plan-empty"><div><strong>Turn this answer into progress</strong><p>Keep next actions here, then record what happened.</p></div><div className="work-plan-controls"><button className="subtle-button" disabled={busy} onClick={record}>Record result</button><button className="subtle-button" disabled={busy} onClick={edit}>Create action plan</button></div></div>}
    {value && <small className="work-disclosure">Completion is recorded by you. Planned dates do not schedule reminders or execute actions.</small>}
    <Dialog open={open} onOpenChange={next => { if (!next) close(); }}><DialogContent className="work-dialog"><DialogTitle>{recording ? 'Record the outcome' : 'Your next actions'}</DialogTitle><DialogDescription>{recording ? 'Record what actually happened. Time estimates are optional and self-reported, not measured automatically.' : 'Choose concrete actions from the answer. Saving a plan does not execute them. It stays with this conversation and follows your account or browser-history save settings.'}</DialogDescription>
      {open && !recording && suggestionContext && !value?.actions.length && <ActionPlanSuggestion context={suggestionContext} busy={busy} onPending={setDrafting} onPreview={setHasPreview} onUse={proposal => { setDraft(current => ({ ...current, goal: proposal.goal, actions: proposal.actions.map(title => ({ id: crypto.randomUUID(), title })) })); setError(''); }} />}
      <form onSubmit={e => { e.preventDefault(); if (busy || drafting) return; save(recording ? { ...draft, outcome: { disposition, correction: reviewed ? correction : 'not-assessed', note, recordedAt: draft.outcome?.recordedAt ?? new Date().toISOString(), ...(minutesSaved !== '' ? { minutesSaved: Number(minutesSaved) } : {}) } } : draft); }}>
        {recording ? <><label>Did you use this result?<select aria-label="Result use" value={disposition} onChange={e => setDisposition(e.target.value as typeof disposition)}><option value="used">Used</option><option value="edited">Used with edits</option><option value="not-used">Not used</option></select></label>{reviewed && <label>Did the team establish a material correction?<select aria-label="Correction assessment" value={correction} onChange={e => setCorrection(e.target.value as typeof correction)}><option value="not-assessed">Not assessed / no correction claimed</option><option value="confirmed">I confirmed a correction</option><option value="rejected">I rejected the proposed correction</option></select><small>Your assessment is recorded as feedback, not proof of correctness.</small></label>}<label>What happened? (optional)<textarea aria-label="Outcome notes" maxLength={2000} value={note} onChange={e => setNote(e.target.value)} placeholder="What was useful, what changed, and what evidence supports your correction assessment?" /></label><label>Estimated minutes saved (optional)<input aria-label="Minutes saved" type="number" min="-100000" max="100000" step="1" value={minutesSaved} onChange={e => setMinutesSaved(e.target.value)} /><small>Use a negative number if this took more time. Leave blank if unknown.</small></label><small>Recording use does not complete any checklist actions. Mark those separately when done.</small></> : <><label>Outcome to work toward<input aria-label="Plan goal" required maxLength={300} value={draft.goal} onChange={e => setDraft({ ...draft, goal: e.target.value })} /></label><div className="work-edit-actions">{draft.actions.map((action, index) => <div className="work-edit-action" key={action.id}><label>Action {index + 1}<input aria-label={`Action ${index + 1}`} required maxLength={240} value={action.title} onChange={e => setDraft({ ...draft, actions: draft.actions.map(a => a.id === action.id ? { ...a, title: e.target.value } : a) })} /></label><label>Planned date<input aria-label={`Planned date ${index + 1}`} type="date" value={action.due ?? ''} onChange={e => setDraft({ ...draft, actions: draft.actions.map(a => { if (a.id !== action.id) return a; const { due, ...rest } = a; return e.target.value ? { ...rest, due: e.target.value } : rest; }) })} /></label><button type="button" className="subtle-button" aria-label={`Remove action ${index + 1}`} onClick={() => setDraft({ ...draft, actions: draft.actions.filter(a => a.id !== action.id) })}>Remove</button></div>)}</div><button className="subtle-button" type="button" disabled={draft.actions.length >= 20} onClick={() => setDraft({ ...draft, actions: [...draft.actions, { id: crypto.randomUUID(), title: '' }] })}>Add action</button><small>Up to 20 actions. Dates are for planning only.</small></>}
        {error && <p role="alert">{error}</p>}<div className="dialog-actions"><button type="button" className="subtle-button" onClick={close}>Cancel</button><button type="submit" className="run-button" disabled={busy || drafting}>{recording ? 'Save outcome' : 'Save action plan'}</button></div>
      </form>
    </DialogContent></Dialog>
    <AlertDialog open={discardOpen} onOpenChange={setDiscardOpen}><AlertDialogContent><AlertDialogTitle>{drafting ? 'Stop drafting and discard this plan?' : 'Discard unsaved plan changes?'}</AlertDialogTitle><AlertDialogDescription>{drafting ? 'A dispatched model request may still be billed. Closing stops waiting for its response and discards this unsaved editor.' : 'The changes and any unused checklist preview in this editor will be discarded. Your saved plan stays unchanged.'}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep editing</AlertDialogCancel><AlertDialogAction onClick={() => { setDiscardOpen(false); setOpen(false); }}>{drafting ? 'Stop and discard' : 'Discard changes'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </section>;
}
