const baseUrl = process.env.TRIO_BASE_URL || 'http://localhost:5173';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'msedge' });
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 }, permissions: ['clipboard-read', 'clipboard-write'] });
const page = await context.newPage();
const errors = []; page.on('pageerror', error => errors.push(error.message));
const result = { drafts: { openai: 'First perspective', claude: 'Second perspective' }, reviews: {}, answer: '', errors: [], seconds: 1, demo: false, usage: { calls: 3, reportedCalls: 2, inputTokens: 200, outputTokens: 40, costUSD: null, byProvider: { openai: { model: 'gpt-6-astra', calls: 3, reportedCalls: 2, inputTokens: 200, outputTokens: 40, costUSD: null } } } };
const session = { id: 'restored-comparison', title: 'Saved comparison', time: new Date().toISOString(), turns: [{ question: 'Saved comparison', mode: 'compare', result }] };
await page.goto(`${baseUrl}/signin-with-chatgpt?return_to=%2Fdemo`, { waitUntil: 'networkidle' });
await page.evaluate(s => {
  localStorage.setItem('trio-remember', 'true');
  localStorage.setItem('trio-sessions', JSON.stringify([{ id: 'broken', turns: [{}] }, s]));
  localStorage.setItem('trio-active-session', s.id);
}, session);
await page.reload({ waitUntil: 'networkidle' });
await page.getByText('First perspective', { exact: true }).waitFor();
assert.equal(await page.locator('.session-list .session-open').count(), 1);
assert.equal(await page.getByRole('tab', { name: 'Perspectives 2' }).getAttribute('data-state'), 'active');
await page.getByRole('button', { name: 'Connections', exact: true }).click();
await page.getByPlaceholder('Paste your API key').nth(0).fill('only-a-test-key');
await page.getByRole('switch', { name: 'Demo mode', exact: true }).click();
await page.getByRole('button', { name: 'Done', exact: true }).click();
const markdown = '# A formatted answer\n\n**Important finding**\n\n- First item\n- Second item\n\n```javascript\nconsole.log("hello");\n' + 'x'.repeat(200) + '\n```\n\n| Model | Result |\n| --- | --- |\n| OpenAI | Ready |\n\n[Documentation](https://example.com/docs)\n\n[Unsafe](javascript:alert(1))\n\n![Tracking](https://example.com/pixel.png)\n\n<script>window.trioUnsafe = true</script>';
let requested = 0;
await page.route('**/api/ask', async route => {
  requested++;
  const body = route.request().postDataJSON();
  assert.deepEqual(body.history.map(m => m.role), ['user', 'assistant']);
  assert.match(body.history[1].content, /First perspective/);
  assert.match(body.history[1].content, /Second perspective/);
  assert.equal(body.connections.openai.key, 'only-a-test-key');
  await route.fulfill({ contentType: 'application/x-ndjson', body: JSON.stringify({ type: 'final', result: { ...result, answer: markdown, by: 'openai' } }) + '\n' });
});
await page.getByRole('textbox', { name: 'Your question' }).fill('Build on both perspectives');
await page.getByRole('button', { name: 'Ask Trio', exact: true }).click();
await page.getByRole('heading', { name: 'A formatted answer' }).waitFor();
await page.getByText('Partial usage · 240 reported tokens').click();
await page.getByText('Usage reported for 2 of 3 calls.', { exact: false }).waitFor();
await page.getByText('Cost unavailable', { exact: true }).waitFor();
await page.getByText('Partial usage · 240 reported tokens').click();
assert.equal(requested, 1);
assert.equal(await page.locator('.prose-answer strong').first().textContent(), 'Important finding');
assert.equal(await page.getByRole('table').count(), 1);
assert.equal(await page.locator('.prose-answer img, .prose-answer script, .prose-answer a[href^="javascript:"]').count(), 0);
assert.equal(await page.evaluate(() => window.trioUnsafe), undefined);
assert.equal(await page.getByRole('link', { name: 'Documentation' }).getAttribute('rel'), 'noopener noreferrer');
await page.getByRole('button', { name: 'Copy code', exact: true }).click();
assert.match(await page.evaluate(() => navigator.clipboard.readText()), /console\.log\("hello"\)/);
assert.ok(!(await page.evaluate(() => JSON.stringify(localStorage))).includes('only-a-test-key'));
await page.reload({ waitUntil: 'networkidle' });
await page.getByRole('heading', { name: 'A formatted answer' }).waitFor();
await page.getByLabel('Choose text context').setInputFiles({ name: 'private-context.txt', mimeType: 'text/plain', buffer: Buffer.from('Do not leak across sessions') });
await page.getByText('private-context.txt').waitFor();
await page.locator('.session-list .session-open').click();
assert.equal(await page.getByText('private-context.txt').count(), 1, 'Selecting the current conversation must preserve its attached context');
await page.getByRole('button', { name: 'Remove attachment', exact: true }).click();
await page.getByRole('button', { name: 'Clear session history' }).click();
await page.getByRole('button', { name: 'Keep sessions' }).click();
await page.getByRole('alertdialog').waitFor({ state: 'hidden' });
assert.equal(await page.locator('.session-list .session-open').count(), 1);
await page.setViewportSize({ width: 390, height: 844 });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Rich output stays inside mobile viewport');
await mkdir('test-output', { recursive: true });
await page.screenshot({ path: 'test-output/rich-answer-mobile.png', fullPage: true });
await page.setViewportSize({ width: 1440, height: 1050 });
await page.screenshot({ path: 'test-output/rich-answer-desktop.png', fullPage: true });
await page.getByRole('button', { name: 'Clear session history' }).click();
await page.getByRole('button', { name: 'Clear all sessions' }).click();
assert.equal(await page.locator('.session-list .session-open').count(), 0);
await page.reload({ waitUntil: 'networkidle' });
assert.equal(await page.locator('.session-list .session-open').count(), 0);
assert.deepEqual(errors, []);
await browser.close();
console.log('Browser quality checks passed: validated restoration, Compare context, Markdown, code copy, safe links, no embedded media, key privacy, attachment isolation, deletion confirmation, mobile layout.');
