const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'msedge' });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
await mkdir('test-output', { recursive: true });
await page.goto('http://localhost:5173/', { waitUntil: 'networkidle' });
await page.getByRole('heading', { name: 'One question. Three perspectives.' }).waitFor();
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
await page.screenshot({ path: 'test-output/desktop.png', fullPage: true });
await page.getByRole('button', { name: 'Run demo', exact: true }).click();
await page.getByText('Make the first 30 days a learning sprint.', { exact: false }).waitFor();
await page.getByRole('tab', { name: 'Perspectives 3' }).click();
await page.getByText('Start with the problem, not the product.', { exact: false }).waitFor();
await page.getByRole('tab', { name: 'Peer reviews 3' }).click();
await page.getByText('Strongest shared idea:', { exact: false }).waitFor();
await page.getByRole('button', { name: 'Connections', exact: true }).click();
await page.getByRole('dialog').waitFor();
const keyInputs = page.getByPlaceholder('Paste your API key');
await keyInputs.nth(0).fill('not-a-real-key');
await page.getByRole('switch', { name: 'Remember sessions on this device' }).click();
assert.ok(!(await page.evaluate(() => JSON.stringify(localStorage))).includes('not-a-real-key'));
await page.getByRole('switch', { name: 'Demo mode', exact: true }).click();
await page.getByRole('button', { name: 'Done', exact: true }).click();
await page.route('**/api/ask', async route => {
  const body = route.request().postDataJSON();
  assert.equal(body.history.length, 0, 'Demo answers must not enter live context');
  assert.equal(body.connections.openai.key, 'not-a-real-key');
  await route.fulfill({ status: 400, contentType: 'application/json', body: JSON.stringify({ error: 'Test validation error' }) });
});
await page.getByRole('textbox', { name: 'Your question' }).fill('A live question');
await page.getByRole('button', { name: 'Ask Trio', exact: true }).click();
await page.getByRole('alert').getByText('Test validation error').waitFor();
await page.reload({ waitUntil: 'networkidle' });
await page.getByRole('button', { name: 'Connections', exact: true }).click();
assert.equal(await page.getByPlaceholder('Paste your API key').nth(0).inputValue(), '');
await page.getByRole('button', { name: 'Close', exact: true }).click();
await page.getByRole('dialog').waitFor({ state: 'hidden' });
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'test-output/mobile.png', fullPage: true });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'No mobile overflow');
const bad = await page.request.post('http://localhost:5173/api/ask', { data: { question: 'x' } });
assert.equal(bad.status(), 400);
const crossOrigin = await page.request.post('http://localhost:5173/api/ask', { headers: { origin: 'https://example.com' }, data: {} });
assert.equal(crossOrigin.status(), 403);
assert.deepEqual(errors, []);
await browser.close();
console.log('Browser checks passed: demo, drafts, reviews, connections, key non-persistence, live error handling, history isolation, mobile layout, API validation, cross-origin rejection.');
