const baseUrl = process.env.TRIO_BASE_URL || 'http://localhost:5173';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'msedge' });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${baseUrl}/signin-with-chatgpt?return_to=%2Fdemo`, { waitUntil: 'networkidle' });
  await page.getByRole('button', { name: 'Run demo', exact: true }).click();
  await page.getByRole('button', { name: 'Run demo', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Connections', exact: true }).click();
  await page.getByPlaceholder('Paste your API key').first().fill('fake-backup-key');
  await page.getByRole('switch', { name: 'Remember sessions on this device', exact: true }).click();
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await page.getByRole('textbox', { name: 'Your question' }).fill('Keep my unsent prompt');
  const open = async () => page.getByRole('button', { name: 'Back up & restore', exact: true }).click();
  const upload = async data => page.getByLabel('Choose workspace backup').setInputFiles({ name: 'workspace.json', mimeType: 'application/json', buffer: Buffer.from(typeof data === 'string' ? data : JSON.stringify(data)) });
  await open();
  const downloadEvent = page.waitForEvent('download'); await page.getByRole('button', { name: 'Download backup', exact: true }).click();
  const download = await downloadEvent; let json = ''; for await (const chunk of await download.createReadStream()) json += chunk;
  assert.ok(!json.includes('fake-backup-key')); const backup = JSON.parse(json);
  assert.equal(backup.sessions.length, 1); assert.equal(backup.version, 5);
  const original = backup.sessions[0];
  await upload(backup); await page.getByText('0 new · 1 already present', { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Import 0 sessions', exact: true }).isDisabled(), true);
  const imported = structuredClone(original); imported.title = 'Imported researched question'; imported.connections = { openai: { key: 'injected-import-key' } };
  imported.turns[0].question = imported.title; imported.turns[0].result.demo = false; imported.turns[0].result.answer = 'Imported answer with complete context';
  imported.turns[0].result.researchRequested = true; imported.turns[0].result.research = { text: 'Evidence [1](https://example.org/report)', sources: [{ title: 'Imported source', url: 'https://example.org/report' }], at: '2026-09-22T00:00:00Z' };
  const mixed = { ...backup, sessions: [imported] };
  await upload(mixed); await page.getByText('1 new · 0 already present · 1 conflicting version kept as a separate copy', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Select none', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Import 0 sessions', exact: true }).isDisabled(), true);
  await page.getByRole('button', { name: 'Select all', exact: true }).click();
  const before = await page.evaluate(() => localStorage.getItem('trio-sessions'));
  assert.equal(JSON.parse(before).length, 1, 'Preview does not mutate history');
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await mkdir('test-output', { recursive: true }); await page.getByRole('dialog').screenshot({ path: 'test-output/backups-mobile.png' });
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.getByRole('button', { name: 'Import 1 session', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: 'Your question' }).inputValue(), 'Keep my unsent prompt');
  const saved = await page.evaluate(() => localStorage.getItem('trio-sessions'));
  assert.equal(JSON.parse(saved).length, 2); assert.deepEqual(JSON.parse(saved)[0], original); assert.ok(!saved.includes('injected-import-key'));
  await page.locator('.session-list').getByRole('button', { name: 'Imported researched question', exact: true }).click();
  await page.getByText('Imported answer with complete context', { exact: true }).waitFor();
  await page.locator('.research-panel summary').click(); await page.getByRole('link', { name: 'Imported source', exact: false }).waitFor();
  await open(); await upload(mixed); await page.getByText('0 new · 1 already present', { exact: true }).waitFor();
  await upload({ ...backup, sessions: [original, { ...imported, id: 'bad', turns: [null] }] });
  await page.getByText('This is not a supported Trio backup, or a session is damaged. Nothing was imported.', { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => localStorage.getItem('trio-sessions')), saved);
  await page.keyboard.press('Escape');
  // Closing the dialog invalidates a delayed read; it cannot resurrect an old preview.
  await page.evaluate(() => { const original = File.prototype.text; File.prototype.text = async function () { const text = await original.call(this); await new Promise(resolve => window.finishBackupRead = resolve); return text; }; });
  await open(); await upload(backup); await page.waitForFunction(() => !!window.finishBackupRead);
  await page.keyboard.press('Escape'); await open(); await page.evaluate(async () => { window.finishBackupRead(); await new Promise(requestAnimationFrame); });
  assert.equal(await page.locator('.backup-preview').count(), 0);
  await page.keyboard.press('Escape'); await page.reload({ waitUntil: 'networkidle' });
  await page.getByText('Imported answer with complete context', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Connections', exact: true }).click(); assert.equal(await page.getByPlaceholder('Paste your API key').first().inputValue(), ''); await page.getByRole('button', { name: 'Done', exact: true }).click();
  // On another device, restore is local and does not turn persistence on or call APIs.
  const other = await browser.newPage({ viewport: { width: 1440, height: 1050 } }); let apiCalls = 0;
  await other.route('**/api/ask', route => { apiCalls++; return route.abort(); });
  await other.goto(`${baseUrl}/signin-with-chatgpt?return_to=%2Fdemo`, { waitUntil: 'networkidle' }); await other.getByRole('button', { name: 'Back up & restore', exact: true }).click();
  await other.getByLabel('Choose workspace backup').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(mixed)) });
  await other.getByText(/Local history is off/).waitFor(); await other.getByRole('button', { name: 'Import 1 session', exact: true }).click();
  assert.equal(await other.evaluate(() => localStorage.getItem('trio-remember')), 'false'); assert.equal(await other.evaluate(() => localStorage.getItem('trio-sessions')), null);
  await other.locator('.session-list').getByRole('button', { name: 'Imported researched question', exact: true }).click(); await other.getByText('Imported answer with complete context', { exact: true }).waitFor();
  assert.equal(apiCalls, 0); assert.deepEqual(errors, []);
  console.log('Backup browser checks passed: download, preview, collision copies, duplicate skipping, invalid files, prompt preservation, late reads, restore, citations, key privacy, mobile, and memory-only imports.');
} finally { await browser.close(); }
