import { getChatGPTUser, chatGPTSignInPath } from './chatgpt-auth';
export const dynamic = 'force-dynamic';
export default async function Welcome() {
  const user = await getChatGPTUser();
  const start = user ? '/workspace' : chatGPTSignInPath('/workspace');
  return <main className="welcome">
    <nav className="welcome-nav"><a className="welcome-brand" href="/">◈ <strong>Trio</strong></a><a className="subtle-button" href={start}>{user ? 'Open workspace' : 'Sign in'}</a></nav>
    <section className="welcome-hero"><p className="welcome-eyebrow">THREE PERSPECTIVES. YOUR NEXT BREAKTHROUGH.</p><h1>Better thinking,<br /><span>together.</span></h1><p className="welcome-intro">Bring ChatGPT, Claude, and Gemini into one conversation. Let them explore, challenge, and refine an answer you can put to work.</p><div className="welcome-actions"><a className="run-button" href={start}>{user ? 'Open your workspace' : 'Get started with ChatGPT'} <span aria-hidden="true">↗</span></a><a className="subtle-button" href="/demo">Explore the demo</a></div><p className="welcome-caption">Sign in with your ChatGPT account. Your conversations belong to your personal workspace.</p></section>
    <section className="welcome-council" aria-label="How Trio works"><article><span className="welcome-number">01 / EXPLORE</span><h2>Three independent takes</h2><p>Ask once. Get distinct perspectives from your connected AI models.</p><div className="welcome-models"><span>ChatGPT</span><span>Claude</span><span>Gemini</span></div></article><article><span className="welcome-number">02 / CHALLENGE</span><h2>Let ideas meet scrutiny</h2><p>Peer reviews surface gaps, assumptions, and useful differences. Deep Council adds a revision round.</p></article><article><span className="welcome-number">03 / CREATE</span><h2>One considered answer</h2><p>Combine the strongest contributions, inspect every step, and continue where you left off.</p></article></section>
    <section className="welcome-details"><div><h2>A workspace that travels with you.</h2><p>Your signed-in history saves online and is isolated from other accounts. Bring questions, images, PDFs, and research into the same conversation.</p></div><div><h3>Your models. Your control.</h3><p>Each person connects their own provider API keys. Keys stay in the current tab and are never saved. Consumer subscriptions do not include API usage; providers bill API requests separately.</p><p>Model agreement is not proof. Review sources and verify important answers.</p></div></section>
    <footer className="welcome-footer"><span>◈ Trio · Collective intelligence</span><a href={start}>Enter your workspace →</a></footer>
  </main>;
}
