'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUp, Plus, MessageSquare, Settings2, Paperclip, X, Copy, Download, Check, Layers3, Zap, GitCompareArrows, ShieldCheck, ChevronRight, Square, Lightbulb, Code2, Compass, CircleHelp, Trash2 } from 'lucide-react';
import { SidebarProvider, Sidebar, SidebarContent, SidebarHeader, SidebarFooter, SidebarTrigger } from '@/components/ui/sidebar';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { Answer as Prose } from '@/components/answer';
import { UsageSummary } from '@/components/usage-summary';
import { parseSessions, conversationHistory, sessionMarkdown, type Turn, type Session } from '@/lib/sessions';
import { Toaster, toast } from 'sonner';
import { providers, freshConnections, type Connections, type Mode, type ProviderId, type Result, type RunEvent } from '@/lib/trio';

const modes = { council: { title: 'Council', icon: Layers3, desc: 'Independent answers, peer review, one stronger result.', calls: 'Up to 7 calls + failover' }, fast: { title: 'Quick synthesis', icon: Zap, desc: 'Three perspectives, combined without the review round.', calls: 'Up to 4 calls + failover' }, compare: { title: 'Compare', icon: GitCompareArrows, desc: 'Independent answers side by side. You make the call.', calls: 'Up to 3 calls' } };
const emptyResult = (demo: boolean): Result => ({ drafts: {}, reviews: {}, errors: [], answer: '', seconds: 0, demo });
const demoQuestion = 'Design a practical 30-day plan to turn an idea into a validated product.';
const demoDrafts = [
  'Start with the problem, not the product.\n\nWeek 1: Interview 8–10 people in one customer segment. Ask about the last time they encountered the problem and how they solve it today.\n\nWeek 2: Test a simple offer before building.\n\nWeek 3: Deliver the core result manually for three pilot users.\n\nWeek 4: Compare repeat use, willingness to pay, and the effort to deliver. Build only what the evidence supports.',
  'Define what would disprove the idea before testing it.\n\nChoose one audience and one painful workflow. Record existing workarounds, their cost, and who owns the buying decision. Avoid asking whether people “like” the idea.\n\nUse a concierge pilot with a clear success measure. Separate polite enthusiasm from a concrete commitment. At day 30, decide whether to continue, change the customer segment, or stop.',
  'Create a small learning loop: observe → prototype → test → measure.\n\nMap the workflow and find the slowest or most frustrating step. Make a clickable prototype around that single step, then test with five prospective users.\n\nTrack task completion and reasons for abandonment. Use a simple experiment log so each week starts with evidence from the previous one. A small sample is directional evidence, not proof of market demand.',
];
const demoReviews = [
  'Strongest shared idea: test one painful problem with a narrow audience.\n\nImprovement: choose the decision criteria before the pilot. Interviews alone do not validate willingness to pay.\n\nOpen question: which audience can you reach in the first week?',
  'The plans agree on a small experiment, but agreement is not external validation.\n\nAvoid treating 8–10 interviews as statistically representative. Capture contradictory evidence, not just positive feedback. Make the stop or pivot decision explicit.',
  'Combine the practical weekly plan with a clear experiment log.\n\nMeasure an actual behavior, such as repeated use or a pilot commitment. Keep the prototype small enough to revise during the month. Pricing and sample size remain assumptions to test.',
];
const demoFinal = 'Make the first 30 days a learning sprint. Your goal is evidence that a specific group will act on your offer.\n\n01 — Find the problem · Days 1–7\nPick one reachable customer segment. Interview 8–10 people about a recent experience, current workarounds, and the cost of the problem. Record evidence that challenges your idea.\n\n02 — Test the offer · Days 8–14\nWrite a one-sentence promise and build a simple prototype. Ask five prospective users to complete the core task. Define a measurable success threshold before you run the pilot.\n\n03 — Deliver the outcome · Days 15–23\nRun a small, hands-on pilot with three users. Deliver the result manually where possible. Track completion, repeated use, time saved, and willingness to commit.\n\n04 — Decide with evidence · Days 24–30\nCompare results with your original threshold. Continue if the behavior supports the idea; revise the audience or offer if it does not. Document what you still do not know.\n\nKeep in mind\nThese sample sizes are a starting point, not statistical validation. Positive feedback is weaker evidence than repeated use or a concrete commitment.\n\nYour first move: name the customer segment and the one problem you want to test.';
function Mark({ id, small = false }: { id?: ProviderId; small?: boolean }) { const p = providers.find(p => p.id === id); return <span className={`model-mark ${small ? 'small' : ''}`} style={{ color: p?.color ?? '#c4bbff', background: (p?.color ?? '#aa99ff') + '14' }}>{p?.mark ?? '◈'}</span>; }

export default function Home() {
  const [connections, setConnections] = useState<Connections>(freshConnections);
  const [settings, setSettings] = useState(false), [help, setHelp] = useState(false);
  const [demo, setDemo] = useState(true), [mode, setMode] = useState<Mode>('council'), [lead, setLead] = useState<ProviderId>('claude');
  const [prompt, setPrompt] = useState(''), [context, setContext] = useState<{ name: string; text: string } | null>(null);
  const [sessions, setSessions] = useState<Session[]>([]), [current, setCurrent] = useState<string | null>(null);
  const [turns, setTurns] = useState<Turn[]>([]), [busy, setBusy] = useState(false), [stage, setStage] = useState('');
  const [working, setWorking] = useState<Result | null>(null), [runningQuestion, setRunningQuestion] = useState(''), [tab, setTab] = useState('answer');
  const [remember, setRemember] = useState(false), [loaded, setLoaded] = useState(false);
  const [clearHistory, setClearHistory] = useState(false), [runMode, setRunMode] = useState<Mode>('council');
  const abortRef = useRef<AbortController | null>(null), fileRef = useRef<HTMLInputElement>(null), promptRef = useRef<HTMLTextAreaElement>(null);
  const connected = providers.filter(p => connections[p.id].key.trim() && connections[p.id].enabled).length;
  useEffect(() => {
    try {
      const enabled = localStorage.getItem('trio-remember') === 'true'; setRemember(enabled);
      if (enabled) {
        const saved = parseSessions(localStorage.getItem('trio-sessions')); setSessions(saved);
        const active = localStorage.getItem('trio-active-session');
        const restored = active === null ? saved[0] : saved.find(s => s.id === active);
        if (restored) { setCurrent(restored.id); setTurns(restored.turns); setStage('done'); setTab(restored.turns.at(-1)?.mode === 'compare' ? 'drafts' : 'answer'); }
      }
    } catch {} setLoaded(true);
  }, []);
  useEffect(() => { if (!loaded) return; try { localStorage.setItem('trio-remember', String(remember)); if (remember) { localStorage.setItem('trio-sessions', JSON.stringify(sessions)); localStorage.setItem('trio-active-session', current ?? ''); } else { localStorage.removeItem('trio-sessions'); localStorage.removeItem('trio-active-session'); } } catch { toast.error('Browser storage is full or unavailable. This session stays in memory.'); } }, [sessions, remember, loaded, current]);
  useEffect(() => () => abortRef.current?.abort(), []);
  function newSession() { if (busy) return; setTurns([]); setCurrent(null); setWorking(null); setPrompt(''); setContext(null); setRunningQuestion(''); promptRef.current?.focus(); }
  function saveTurn(question: string, result: Result) { const next = [...turns, { question, result, mode }]; setTurns(next); const id = current ?? crypto.randomUUID(); setCurrent(id); setSessions(prev => [{ id, title: next[0].question, turns: next, time: new Date().toISOString() }, ...prev.filter(s => s.id !== id)].slice(0, 30)); }
  async function delay(ms: number, signal: AbortSignal) { await new Promise<void>((resolve, reject) => { if (signal.aborted) return reject(new DOMException('Cancelled', 'AbortError')); const cancel = () => { clearTimeout(timer); reject(new DOMException('Cancelled', 'AbortError')); }; const timer = setTimeout(() => { signal.removeEventListener('abort', cancel); resolve(); }, ms); signal.addEventListener('abort', cancel, { once: true }); }); }
  async function run() {
    if (busy) return;
    const question = demo ? demoQuestion : prompt.trim();
    if (!question) return;
    if (!demo && !connected) { setSettings(true); toast('Add an API key to start a live session.'); return; }
    setBusy(true); setRunMode(mode); setStage('draft'); setWorking(emptyResult(demo)); setRunningQuestion(question); setTab(mode === 'compare' ? 'drafts' : 'answer');
    const controller = new AbortController(); abortRef.current = controller;
    let result = emptyResult(demo), completed = false;
    try {
      if (demo) {
        for (let i = 0; i < providers.length; i++) { await delay(500, controller.signal); result = { ...result, drafts: { ...result.drafts, [providers[i].id]: demoDrafts[i] } }; setWorking(result); }
        if (mode === 'council') { setStage('review'); for (let i = 0; i < providers.length; i++) { await delay(400, controller.signal); result = { ...result, reviews: { ...result.reviews, [providers[i].id]: demoReviews[i] } }; setWorking(result); } }
        if (mode !== 'compare') { setStage('synthesis'); await delay(700, controller.signal); result = { ...result, answer: demoFinal, by: lead }; }
        result.seconds = mode === 'council' ? 3.4 : mode === 'fast' ? 2.2 : 1.5; completed = true;
      } else {
        const history = conversationHistory(turns);
        const response = await fetch('/api/ask', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question, context: context?.text, history, connections, mode, lead }), signal: controller.signal });
        if (!response.ok) { const data = await response.json() as { error?: string }; throw new Error(data.error ?? 'Could not start this session.'); }
        const reader = response.body!.getReader(), decoder = new TextDecoder(); let buffer = '';
        const consume = (line: string) => {
          if (!line.trim()) return; const event: RunEvent = JSON.parse(line);
          if (event.type === 'stage') setStage(event.stage!);
          if ((event.type === 'draft' || event.type === 'review') && event.provider) { const bucket = event.type === 'draft' ? 'drafts' : 'reviews'; result = { ...result, [bucket]: { ...result[bucket], [event.provider]: event.text } }; }
          if (event.type === 'error') result = { ...result, errors: [...result.errors, event.text!] };
          if (event.type === 'usage' && event.usage) result = { ...result, usage: event.usage };
          if (event.type === 'final' && event.result) { result = event.result; completed = true; }
          setWorking({ ...result });
        };
        while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const lines = buffer.split('\n'); buffer = lines.pop()!; lines.forEach(consume); }
        buffer += decoder.decode(); if (buffer.trim()) consume(buffer);
        if (!completed) throw new Error(result.errors.at(-1) ?? 'Connection interrupted. Try again.');
      }
      saveTurn(question, result); setWorking(null); setRunningQuestion(''); if (!demo) setPrompt(''); setStage('done');
    } catch (error) { if (controller.signal.aborted) { toast('Session stopped. No result was saved.'); setWorking({ ...result, errors: [...result.errors, 'Session stopped. Partial contributions are shown below.'] }); } else { const text = error instanceof Error ? error.message : 'Something went wrong.'; toast.error(text); setWorking({ ...result, errors: [...result.errors, text] }); } setStage('failed'); }
    finally { setBusy(false); abortRef.current = null; }
  }
  async function attach(file?: File) { if (!file) return; if (!/\.(txt|md|csv|json|js|ts|tsx|py|html|css)$/i.test(file.name)) return toast.error('Choose a text, Markdown, CSV, JSON, or code file.'); if (file.size > 60000) return toast.error('Use a text file smaller than 60 KB.'); const text = await file.text(); setContext({ name: file.name, text }); }
  async function copy(text: string) { try { await navigator.clipboard.writeText(text); toast.success('Copied to clipboard'); } catch { toast.error('Clipboard unavailable. Select and copy the answer manually.'); } }
  function exportSession() { const url = URL.createObjectURL(new Blob([sessionMarkdown(turns)], { type: 'text/markdown' })); const a = document.createElement('a'); a.href = url; a.download = 'trio-session.md'; a.click(); URL.revokeObjectURL(url); }
  const displayed = working ?? turns.at(-1)?.result;
  const question = runningQuestion || turns.at(-1)?.question;
  const displayMode = working ? runMode : turns.at(-1)?.mode ?? mode;

  return <SidebarProvider style={{ '--sidebar-width': '248px' } as React.CSSProperties}>
    <Sidebar className="trio-sidebar">
      <SidebarHeader className="brand"><span className="brand-symbol">◈</span><span>trio<span className="brand-period">.</span></span><span className="brand-caption">WORKSPACE</span></SidebarHeader>
      <SidebarContent className="side-content">
        <button className="new-session" onClick={newSession} disabled={busy}><Plus size={17} /> New session <span>↗</span></button>
        <div className="side-label">YOUR WORKSPACE</div>
        <button className="side-nav selected" onClick={() => promptRef.current?.focus()}><Layers3 size={17} /> Collective intelligence</button>
        <button className="side-nav" onClick={() => setSettings(true)}><Settings2 size={17} /> Model connections <span className="nav-count">{connected}/3</span></button>
        <div className="history-heading"><span className="side-label">RECENT SESSIONS</span>{sessions.length > 0 && <button aria-label="Clear session history" disabled={busy} onClick={() => setClearHistory(true)}><Trash2 size={14} /></button>}</div>
        <div className="session-list">{sessions.length ? sessions.map(s => <button key={s.id} disabled={busy} className={s.id === current ? 'active' : ''} onClick={() => { setCurrent(s.id); setTurns(s.turns); setWorking(null); setRunningQuestion(''); setPrompt(''); setContext(null); setStage('done'); setTab(s.turns.at(-1)?.mode === 'compare' ? 'drafts' : 'answer'); }}><MessageSquare size={15} /><span>{s.title}</span></button>) : <p className="history-empty">Good ideas start with a question.<br />Your sessions will appear here.</p>}</div>
        <div className="sidebar-bottom-card"><span className="tiny-orbits">◎ <span>✳</span> ✦</span><strong>Different perspectives.<br />A stronger answer.</strong><p>Independent thinking.<br />Collective intelligence.</p><button onClick={() => setHelp(true)}>How Trio works <ChevronRight size={14} /></button></div>
      </SidebarContent>
      <SidebarFooter className="sidebar-foot"><span className="avatar">Y</span><div>Your workspace<small><ShieldCheck size={12} /> Private by default</small></div><button aria-label="About Trio" onClick={() => setHelp(true)}><CircleHelp size={17} /></button></SidebarFooter>
    </Sidebar>
    <main className="workspace">
      <header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu" /><span>Workspace</span><ChevronRight size={14} /><strong>New possibilities</strong></div><div className="top-actions"><span className={`mode-badge ${demo ? '' : 'live'}`}>{demo ? 'Demo workspace' : 'Live workspace'}</span><button className="subtle-button" onClick={() => setSettings(true)}><Settings2 size={15} /><span>Connections</span></button></div></header>
      <div className="work-body">
        <div className="page-intro"><div><div className="eyebrow"><span className="mini-line" /> COLLECTIVE INTELLIGENCE</div><h1>One question. <span>Three perspectives.</span></h1><p>Bring your biggest ideas. Let the best minds work together.</p></div><span className="intro-symbol" aria-hidden>◈</span></div>
        <section className="models-grid" aria-label="Your AI team">{providers.map(p => <button key={p.id} className={`model-card ${!connections[p.id].enabled && !demo ? 'muted-card' : ''}`} onClick={() => setSettings(true)} style={{ '--model-color': p.color } as React.CSSProperties}><div className="model-card-top"><Mark id={p.id} /><span className="provider-status">{busy ? (working?.drafts[p.id] ? 'Contributed' : !demo && (!connections[p.id].enabled || !connections[p.id].key) ? 'Not participating' : 'Working…') : demo ? 'Demo' : connections[p.id].enabled && connections[p.id].key ? 'Key added' : 'Not connected'}</span></div><div className="model-name">{p.name}<span>{p.company}</span></div><p>{p.id === 'openai' ? 'Explore possibilities. Build the plan.' : p.id === 'claude' ? 'Examine the details. Challenge assumptions.' : 'Connect ideas. Find a fresh perspective.'}</p><div className="model-card-foot"><span>{demo ? 'Illustrative participant' : connections[p.id].model}</span><Plus size={14} /></div></button>)}</section>
        <section className="prompt-section"><div className="section-heading"><h2>{turns.length ? 'Keep the conversation going' : 'What are we working on?'}</h2><span>01 / ASK</span></div><div className="composer"><textarea ref={promptRef} value={prompt} maxLength={20000} disabled={busy} onChange={e => setPrompt(e.target.value)} onKeyDown={e => { if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') { e.preventDefault(); void run(); } }} placeholder="A complex question, an ambitious idea, a problem worth solving…" aria-label="Your question" /><div className="composer-bottom"><input ref={fileRef} type="file" accept=".txt,.md,.csv,.json,.js,.ts,.tsx,.py,.html,.css" hidden onChange={e => { void attach(e.target.files?.[0]); e.target.value = ''; }} /><button className="attach-button" onClick={() => fileRef.current?.click()} disabled={busy} title="Attach a text file"><Paperclip size={17} /><span>Add context</span></button>{context && <span className="attachment">{context.name}<button aria-label="Remove attachment" disabled={busy} onClick={() => setContext(null)}><X size={13} /></button></span>}<span className="key-hint">⌘ / Ctrl + Enter</span>{busy ? <button className="run-button" onClick={() => abortRef.current?.abort()}><Square size={14} /> Stop</button> : <button className="run-button" disabled={!demo && !prompt.trim()} onClick={() => void run()}>{demo ? 'Run demo' : 'Ask Trio'}<ArrowUp size={17} /></button>}</div></div><div className="composer-note">{demo ? <>Demo runs a prepared product-validation example. <button onClick={() => setSettings(true)}>Connect models to ask your own question <ChevronRight size={12} /></button></> : <>Prompts and attached text go to enabled providers. {modes[mode].calls}; each provider bills separately.</>}</div></section>
        <section className="collaboration-settings"><div className="flow-label"><span>COLLABORATION MODE</span><small>{modes[mode].desc}</small></div><Tabs value={mode} onValueChange={v => setMode(v as Mode)}><TabsList className="mode-tabs">{Object.entries(modes).map(([key, m]) => <TabsTrigger key={key} value={key} disabled={busy}><m.icon size={15} />{m.title}</TabsTrigger>)}</TabsList></Tabs></section>
        {!displayed && <section className="starter-section"><div className="section-heading"><h2>A starting point for your next big thing</h2><span>TRY AN IDEA</span></div><div className="ideas-grid">{[{ icon: Lightbulb, label: 'Shape an idea', text: 'Turn a rough idea into a real plan.', prompt: demoQuestion }, { icon: Code2, label: 'Build something', text: 'Solve a technical challenge together.', prompt: 'Design a secure, simple architecture for a team knowledge-sharing app. Compare the tradeoffs and propose an implementation plan.' }, { icon: Compass, label: 'Think it through', text: 'See a decision from every angle.', prompt: 'Help me decide whether to build a custom tool or buy existing software. Create a decision framework and identify the questions I should answer first.' }].map(item => <button key={item.label} onClick={() => { setPrompt(item.prompt); if (demo && item.prompt !== demoQuestion) toast('Connect models to run this prompt live. Demo uses the product-validation example.'); promptRef.current?.focus(); }}><item.icon size={19} /><strong>{item.label}<ChevronRight size={15} /></strong><p>{item.text}</p></button>)}</div></section>}
        {displayed && <section className="results-section"><div className="question-title"><MessageSquare size={17} /><h2>{question}</h2></div>{displayed.demo && <div className="demo-notice">ILLUSTRATIVE DEMO · Prepared sample responses. No model APIs were called.</div>}<div className="pipeline" aria-live="polite">{['draft', ...(displayMode === 'council' ? ['review'] : []), ...(displayMode !== 'compare' ? ['synthesis'] : [])].map((s, i) => <div key={s} className={busy && stage === s ? 'current' : !busy && stage !== 'failed' ? 'complete' : ''}><span>{!busy && stage !== 'failed' ? <Check size={13} /> : `0${i + 1}`}</span>{s === 'draft' ? 'Independent thinking' : s === 'review' ? 'Peer review' : 'Combined answer'}{busy && stage === s && <i className="pulse-dot" />}</div>)}</div>
          <Tabs value={tab} onValueChange={setTab}><div className="result-toolbar"><TabsList className="result-tabs"><TabsTrigger value="answer">Synthesis</TabsTrigger><TabsTrigger value="drafts">Perspectives <span>{Object.keys(displayed.drafts).length}</span></TabsTrigger><TabsTrigger value="reviews">Peer reviews <span>{Object.keys(displayed.reviews).length}</span></TabsTrigger></TabsList><div className="result-actions"><button aria-label="Copy answer" disabled={!displayed.answer} onClick={() => void copy(displayed.answer)}><Copy size={16} /></button><button aria-label="Export session as Markdown" disabled={!turns.length || busy} onClick={exportSession}><Download size={16} /></button></div></div>
          <TabsContent value="answer"><div className="answer-card"><div className="answer-heading"><Mark small /><div><strong>{displayed.fallback ? 'Single-model fallback' : 'The collective answer'}</strong><small>{busy ? 'Your team is working on it…' : displayed.by ? `${displayed.fallback ? 'Answered' : 'Combined'} by ${providers.find(p => p.id === displayed.by)?.name} · ${displayed.seconds}s${displayed.demo ? ' · sample' : ''}` : 'Independent perspectives'}</small></div><span className="answer-tag">{displayed.demo ? 'DEMO' : 'TRIO'}</span></div>{displayed.answer ? <Prose text={displayed.answer} /> : <div className="answer-empty">{busy ? <><span className="loading-bar" />{stage === 'draft' ? 'Gathering independent perspectives…' : stage === 'review' ? 'Checking the answers for gaps and disagreements…' : 'Combining the strongest ideas…'}</> : displayMode === 'compare' ? <>Compare mode keeps each perspective independent. <button onClick={() => setTab('drafts')}>Read the perspectives →</button></> : 'No combined answer yet. Check the messages below, then retry.'}</div>}</div></TabsContent>
          <TabsContent value="drafts"><div className="perspective-grid">{providers.map(p => <article key={p.id} className="perspective-card"><div><Mark small id={p.id} /><strong>{p.name}</strong></div>{displayed.drafts[p.id] ? <Prose text={displayed.drafts[p.id]!} /> : <p className="muted">{busy ? 'Waiting for this perspective…' : 'No contribution from this model.'}</p>}</article>)}</div></TabsContent>
          <TabsContent value="reviews"><div className="perspective-grid">{Object.keys(displayed.reviews).length ? providers.filter(p => displayed.reviews[p.id]).map(p => <article key={p.id} className="perspective-card"><div><Mark small id={p.id} /><strong>{p.name}’s review</strong></div><Prose text={displayed.reviews[p.id]!} /></article>) : <p className="muted">{displayMode === 'council' ? 'Reviews appear after at least two models finish their drafts.' : 'Choose Council mode to include peer review in your next run.'}</p>}</div></TabsContent></Tabs>
          {displayed.usage && !displayed.demo && <UsageSummary usage={displayed.usage} />}
          {displayed.errors.length > 0 && <div className="error-box" role="alert"><strong>Some steps could not finish</strong>{Array.from(new Set(displayed.errors)).map((e, i) => <p key={i}>{e}</p>)}<button onClick={() => setSettings(true)}>Check connections</button></div>}
          {turns.length > 1 && <details className="previous-turns"><summary>{turns.length - 1} earlier {turns.length === 2 ? 'question' : 'questions'} in this session</summary>{turns.slice(0, -1).map((t, i) => <article key={i}><h3>{t.question}</h3><Prose text={t.result.answer || 'Independent answers available in the session export.'} /></article>)}</details>}
        </section>}
        <footer className="workspace-footer"><span><ShieldCheck size={13} /> Your keys. Your workspace.</span><span>Different models can make the same mistake. Verify important answers.</span></footer>
      </div>
    </main>
    <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="connections-dialog"><DialogTitle>Connect your AI team</DialogTitle><DialogDescription>Use API keys from each provider. Consumer subscriptions and API billing are separate. Keys stay in this tab’s memory and are sent securely to the server only to make your requests.</DialogDescription><div className="connection-mode"><div><strong>Demo mode</strong><p>Explore the workflow with prepared examples.</p></div><Switch checked={demo} disabled={busy} onCheckedChange={setDemo} aria-label="Demo mode" /></div>{providers.map(p => <div className="connection-row" key={p.id}><div className="connection-header"><Mark id={p.id} small /><strong>{p.name}</strong><a href={p.id === 'openai' ? 'https://platform.openai.com/api-keys' : p.id === 'claude' ? 'https://platform.claude.com/settings/keys' : 'https://aistudio.google.com/apikey'} target="_blank" rel="noreferrer">Get API key ↗</a><Switch aria-label={`Enable ${p.name}`} disabled={busy} checked={connections[p.id].enabled} onCheckedChange={enabled => setConnections(c => ({ ...c, [p.id]: { ...c[p.id], enabled } }))} /></div><label>API key<input type="password" autoComplete="off" spellCheck={false} disabled={busy} placeholder="Paste your API key" value={connections[p.id].key} onChange={e => setConnections(c => ({ ...c, [p.id]: { ...c[p.id], key: e.target.value.trim() } }))} /></label><label>Model ID<input value={connections[p.id].model} disabled={busy} spellCheck={false} onChange={e => setConnections(c => ({ ...c, [p.id]: { ...c[p.id], model: e.target.value.trim() } }))} /></label></div>)}<div className="lead-setting"><label>Preferred synthesis model</label><Select value={lead} onValueChange={v => setLead(v as ProviderId)} disabled={busy}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{providers.map(p => <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div><div className="connection-mode"><div><strong>Remember sessions on this device</strong><p>Stores prompts and answers locally. API keys are never saved.</p></div><Switch checked={remember} onCheckedChange={setRemember} aria-label="Remember sessions on this device" /></div><div className="dialog-actions"><button className="subtle-button" disabled={busy} onClick={() => { setConnections(freshConnections()); setDemo(true); toast('API keys cleared'); }}>Clear keys</button><button className="run-button" onClick={() => { setSettings(false); if (!demo && !connected) toast('Add at least one API key to run live.'); }}>Done<Check size={15} /></button></div></DialogContent></Dialog>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogTitle>Three minds. One workspace.</DialogTitle><DialogDescription>Trio coordinates OpenAI, Anthropic, and Google model APIs.</DialogDescription><div className="help-steps"><p><strong>01 · Think independently</strong>Each enabled model answers your question with the same context.</p><p><strong>02 · Challenge the answers</strong>Council mode asks each model to review anonymized drafts and flag gaps or disagreements.</p><p><strong>03 · Bring it together</strong>Your preferred model writes the final answer. If it fails, another participating model takes over.</p><p>Trio currently supports text, code, and text-file context. It does not browse the web, execute code, or generate images. A shared answer can still be wrong.</p><p>API usage is billed by each provider. Connect only the models you want to use. Sessions stay in memory unless you enable local history.</p></div></DialogContent></Dialog>
    <AlertDialog open={clearHistory} onOpenChange={setClearHistory}><AlertDialogContent><AlertDialogTitle>Clear session history?</AlertDialogTitle><AlertDialogDescription>This removes all saved sessions from this device and clears the current conversation. Export any answers you want to keep first.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep sessions</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={() => { setSessions([]); newSession(); toast('Session history cleared'); }}>Clear all sessions</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Toaster theme="dark" position="bottom-right" richColors />
  </SidebarProvider>;
}
